
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 11;
  public static final int STRING_CONST = 31;
  public static final int AND = 7;
  public static final int NE = 19;
  public static final int LT = 13;
  public static final int PLUS = 9;
  public static final int INT = 20;
  public static final int OR = 8;
  public static final int SEMI = 5;
  public static final int NOT = 6;
  public static final int TRUE = 27;
  public static final int GT = 15;
  public static final int ID = 25;
  public static final int LE = 14;
  public static final int INT_CONST = 29;
  public static final int STRING = 23;
  public static final int COMMA = 3;
  public static final int FLOAT = 22;
  public static final int EOF = 0;
  public static final int DIV = 12;
  public static final int FALSE = 28;
  public static final int GE = 16;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int FLOAT_CONST = 30;
  public static final int EQ = 18;
  public static final int ASSIGN = 17;
  public static final int BOOL = 21;
  public static final int RPAR = 4;
  public static final int NULL = 26;
  public static final int VOID = 24;
  public static final int LPAR = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAR",
  "COMMA",
  "RPAR",
  "SEMI",
  "NOT",
  "AND",
  "OR",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "LT",
  "LE",
  "GT",
  "GE",
  "ASSIGN",
  "EQ",
  "NE",
  "INT",
  "BOOL",
  "FLOAT",
  "STRING",
  "VOID",
  "ID",
  "NULL",
  "TRUE",
  "FALSE",
  "INT_CONST",
  "FLOAT_CONST",
  "STRING_CONST"
  };
}

